"""Cross-framework golden gates against mbirjax.

Golden data is generated by tests/generate_goldens.py IN THE MBIRJAX ENV and
read here (this env never imports jax).  Tolerances: 1e-4 rel-max for single
ops, 1e-3 for iterated/composed results; the measured values are printed so
the floors stay observable.

Comparisons run on CPU (the deterministic-per-process backend); device
coverage is test_adjoint / test_recon_smoke's job.
"""

import glob
import os

import numpy as np
import pytest
import torch

import mbirtorch

GOLDEN_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "goldens")
_paths = sorted(glob.glob(os.path.join(GOLDEN_DIR, "golden_*.npz")))

pytestmark = [pytest.mark.goldens, pytest.mark.skipif(
    not _paths, reason="no goldens: run tests/generate_goldens.py in the mbirjax env")]


@pytest.fixture(scope="module")
def golden():
    return np.load(_paths[0])


@pytest.fixture(scope="module")
def model(golden):
    cell = tuple(int(x) for x in golden["cell"])
    _model = mbirtorch.ParallelBeamModel(cell, golden["angles"])
    _model.configure_devices(devices=["cpu"])
    return _model


def _rel_max(out, ref):
    out = np.asarray(out, dtype=np.float64)
    ref = np.asarray(ref, dtype=np.float64)
    return float(np.max(np.abs(out - ref)) / np.max(np.abs(ref)))


def test_recon_shape_matches(golden, model):
    assert tuple(model.get_params("recon_shape")) == tuple(int(x) for x in golden["recon_shape"])


def test_sparse_forward(golden, model):
    out = model.sparse_forward_project(golden["voxel_values"], golden["subset"])
    err = _rel_max(out.numpy(), golden["sparse_fwd"])
    print(f"sparse_fwd rel_max = {err:.2e}")
    assert err < 1e-4


def test_sparse_back(golden, model):
    out = model.sparse_back_project(golden["sinogram"], golden["subset"])
    err = _rel_max(out.numpy(), golden["sparse_back"])
    print(f"sparse_back rel_max = {err:.2e}")
    assert err < 1e-4


def test_qggmrf_gradient_and_hessian(golden, model):
    recon_shape = tuple(int(x) for x in golden["recon_shape"])
    flat = torch.as_tensor(golden["phantom"].reshape(-1, recon_shape[2]))
    subset = torch.as_tensor(golden["subset"], dtype=torch.int64)
    b = mbirtorch.get_b_from_nbr_wts(model.get_params("qggmrf_nbr_wts"))
    sigma_x = float(golden["qggmrf_sigma_x"])
    p, q, T = model.get_params(["p", "q", "T"])
    grad, hess = mbirtorch.qggmrf_gradient_and_hessian_at_indices(
        flat, recon_shape, subset, (b, sigma_x, p, q, T))
    g_err = _rel_max(grad.numpy(), golden["qg_grad"])
    h_err = _rel_max(hess.numpy(), golden["qg_hess"])
    print(f"qggmrf grad rel_max = {g_err:.2e}, hess rel_max = {h_err:.2e}")
    assert g_err < 1e-4 and h_err < 1e-4


def test_hessian_diagonal(golden, model):
    out = model.compute_hessian_diagonal(weights=torch.as_tensor(golden["weights"]))
    err = _rel_max(out, golden["hessian_diag"])
    print(f"hessian_diag rel_max = {err:.2e}")
    assert err < 1e-4


def test_fbp(golden, model):
    out = model.fbp_recon(golden["sinogram"])
    err = _rel_max(out, golden["fbp"])
    print(f"fbp rel_max = {err:.2e}")
    assert err < 1e-3


def test_auto_regularization(golden, model):
    reg = model.auto_set_regularization_params(golden["sinogram"],
                                               weights=golden["weights"])
    for name, key in (("sigma_y", "sigma_y"), ("sigma_x", "sigma_x_auto"),
                      ("sigma_prox", "sigma_prox")):
        rel = abs(reg[name] - float(golden[key])) / abs(float(golden[key]))
        print(f"{name}: torch {reg[name]:.6g} vs jax {float(golden[key]):.6g} "
              f"(rel {rel:.2e})")
        assert rel < 1e-4, name


def test_recon_convergence_parity(golden, model):
    """Seeded recon matches mbirjax iteration for iteration: same partitions,
    same subset order (the shared numpy RNG), traces at loose tolerance, final
    volume at the iterated tolerance."""
    model.set_params(no_warning=True, verbose=0)
    np.random.seed(int(golden["recon_seed"]))
    recon, recon_dict = model.recon(
        golden["sinogram"], weights=golden["weights"],
        max_iterations=int(golden["max_iterations"]),
        stop_threshold_change_pct=0.0)
    rp = recon_dict["recon_params"]

    alpha = np.array(rp["alpha_values"])
    fm = np.array(rp["fm_rmse"])
    nmae = np.array(rp["stop_threshold_change_pct"])
    alpha_rel = np.max(np.abs(alpha - golden["alpha_values"])
                       / np.abs(golden["alpha_values"]))
    fm_rel = np.max(np.abs(fm - golden["fm_rmse"]) / np.abs(golden["fm_rmse"]))
    nmae_rel = np.max(np.abs(nmae - golden["nmae_pct"]) / np.abs(golden["nmae_pct"]))
    final_rel = _rel_max(recon, golden["recon"])
    print(f"alpha trace rel = {alpha_rel:.2e}, fm_rmse rel = {fm_rel:.2e}, "
          f"nmae rel = {nmae_rel:.2e}, final recon rel_max = {final_rel:.2e}")
    assert alpha_rel < 1e-2
    assert fm_rel < 1e-3
    assert nmae_rel < 1e-3
    assert final_rel < 1e-3
