"""Golden parity gates for mbirtorch.preprocess against mbirjax.

Golden data is generated by tests/generate_preprocess_goldens.py IN THE
MBIRJAX ENV and read here (this env never imports jax).  Gates start at 1e-5
rel-max for the deterministic device chains; the measured values are printed
so the floors stay observable.  Host-side numpy/scipy paths (crop, background
offset, beam hardening, helpers) share code with mbirjax and gate tighter.

Functions with a batch_size parameter also get a batch-invariance test (two
batch sizes, same result) -- the cheap guard against seam bugs in the
batching driver.

Comparisons run on CPU (the deterministic-per-process backend).
"""

import os

import h5py
import numpy as np
import pytest
import torch

import mbirtorch
import mbirtorch.preprocess as mtp
from mbirtorch.preprocess import pipeline

GOLDEN_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "goldens")
_npz_path = os.path.join(GOLDEN_DIR, "preprocess_goldens.npz")
_h5_path = os.path.join(GOLDEN_DIR, "preprocess_goldens_cone_save.h5")

pytestmark = [pytest.mark.goldens, pytest.mark.skipif(
    not os.path.exists(_npz_path),
    reason="no preprocess goldens: run tests/generate_preprocess_goldens.py in the mbirjax env")]


@pytest.fixture(scope="module")
def golden():
    return np.load(_npz_path)


@pytest.fixture(autouse=True)
def _cpu_device(monkeypatch):
    monkeypatch.setattr(pipeline, "_resolve_device", lambda device: torch.device("cpu"))


def _rel_max(out, ref):
    out = np.asarray(out, dtype=np.float64)
    ref = np.asarray(ref, dtype=np.float64)
    return float(np.max(np.abs(out - ref)) / max(np.max(np.abs(ref)), 1e-30))


def test_compute_sino_transmission(golden):
    out = mtp.compute_sino_transmission(golden["obj"].copy(), golden["blank"].copy(),
                                        golden["dark"].copy(),
                                        defective_pixel_array=golden["defective"].copy(),
                                        batch_size=5)
    err = _rel_max(out, golden["sino_trans"])
    print(f"transmission rel_max = {err:.2e}")
    assert err < 1e-5


def test_transmission_batch_invariance(golden):
    a = mtp.compute_sino_transmission(golden["obj"].copy(), golden["blank"].copy(),
                                      golden["dark"].copy(),
                                      defective_pixel_array=golden["defective"].copy(),
                                      batch_size=4)
    b = mtp.compute_sino_transmission(golden["obj"].copy(), golden["blank"].copy(),
                                      golden["dark"].copy(),
                                      defective_pixel_array=golden["defective"].copy(),
                                      batch_size=13)
    assert np.array_equal(a, b)


def test_interpolate_defective_pixels(golden):
    out = mtp.interpolate_defective_pixels(golden["corrupt"].copy(),
                                           defective_pixel_array=golden["defective"].copy(),
                                           num_passes=3)
    assert isinstance(out, np.ndarray)
    err = _rel_max(out, golden["interp"])
    print(f"interpolate rel_max = {err:.2e}")
    assert err < 1e-5


def test_correct_det_rotation(golden):
    out = mtp.correct_det_rotation(golden["sino_trans"].copy(),
                                   det_rotation=float(golden["det_rotation"]), batch_size=4)
    err = _rel_max(out, golden["rotated"])
    print(f"rotation rel_max = {err:.2e}")
    assert err < 1e-5


def test_rotation_batch_invariance(golden):
    a = mtp.correct_det_rotation(golden["sino_trans"].copy(),
                                 det_rotation=float(golden["det_rotation"]), batch_size=3)
    b = mtp.correct_det_rotation(golden["sino_trans"].copy(),
                                 det_rotation=float(golden["det_rotation"]), batch_size=13)
    assert np.array_equal(a, b)


def test_correct_background_offset(golden):
    out_g = mtp.correct_background_offset(golden["sino_trans"].copy(), edge_width=3, option='global')
    out_p = mtp.correct_background_offset(golden["sino_trans"].copy(), edge_width=3, option='per_view')
    err_g = _rel_max(out_g, golden["bg_global"])
    err_p = _rel_max(out_p, golden["bg_per_view"])
    print(f"background rel_max = {err_g:.2e} (global), {err_p:.2e} (per_view)")
    assert err_g < 1e-6 and err_p < 1e-6
    same = golden["sino_trans"]
    assert mtp.correct_background_offset(same, option=None) is same


def test_downsample_view_data(golden):
    obj, blank, dark, defective = mtp.downsample_view_data(
        golden["obj"].copy(), golden["blank"].copy(), golden["dark"].copy(), (2, 2),
        defective_pixel_array=golden["defective"].copy(), batch_size=5)
    err = _rel_max(obj, golden["ds_obj"])
    print(f"downsample rel_max = {err:.2e}")
    assert err < 1e-5
    assert _rel_max(blank, golden["ds_blank"]) < 1e-6
    assert _rel_max(dark, golden["ds_dark"]) < 1e-6 or golden["ds_dark"].max() == 0
    defective = np.asarray(defective) if len(defective) else np.zeros((0, 2), dtype=np.int64)
    assert np.array_equal(defective, golden["ds_defective"])


def test_downsample_batch_invariance(golden):
    a = mtp.downsample_view_data(golden["obj"].copy(), golden["blank"].copy(),
                                 golden["dark"].copy(), (2, 2),
                                 defective_pixel_array=golden["defective"].copy(), batch_size=2)[0]
    b = mtp.downsample_view_data(golden["obj"].copy(), golden["blank"].copy(),
                                 golden["dark"].copy(), (2, 2),
                                 defective_pixel_array=golden["defective"].copy(), batch_size=13)[0]
    assert np.array_equal(a, b)


def test_crop_view_data(golden):
    obj, blank, dark, defective = mtp.crop_view_data(
        golden["obj"].copy(), golden["blank"].copy(), golden["dark"].copy(),
        crop_pixels_sides=2, crop_pixels_top=3, crop_pixels_bottom=1,
        defective_pixel_array=golden["defective"].copy())
    assert np.array_equal(obj, golden["cr_obj"])
    assert np.array_equal(blank, golden["cr_blank"])
    assert np.array_equal(dark, golden["cr_dark"])
    defective = np.asarray(defective) if len(defective) else np.zeros((0, 2), dtype=np.int64)
    assert np.array_equal(defective, golden["cr_defective"])


def test_scan_to_sino(golden):
    out = mtp.scan_to_sino(golden["obj"].copy(), golden["blank"].copy(), golden["dark"].copy(),
                           defective_pixel_array=golden["defective"].copy(),
                           downsample_factor=(2, 2),
                           det_rotation=float(golden["det_rotation"]), batch_size=5)
    err = _rel_max(out, golden["fused"])
    print(f"scan_to_sino rel_max = {err:.2e}")
    assert err < 1e-5


def test_scan_to_sino_batch_invariance(golden):
    kwargs = dict(defective_pixel_array=golden["defective"].copy(), downsample_factor=(2, 2),
                  det_rotation=float(golden["det_rotation"]))
    a = mtp.scan_to_sino(golden["obj"].copy(), golden["blank"].copy(), golden["dark"].copy(),
                         batch_size=3, **kwargs)
    b = mtp.scan_to_sino(golden["obj"].copy(), golden["blank"].copy(), golden["dark"].copy(),
                         batch_size=13, **kwargs)
    assert np.array_equal(a, b)


def test_correct_zinger_pixels(golden):
    out = mtp.correct_zinger_pixels(golden["zinger_in"].copy(), zinger_pixel_ratio=0.1,
                                    num_passes=3, batch_size=5)
    err = _rel_max(out, golden["zinger_out"])
    print(f"zinger rel_max = {err:.2e}")
    assert err < 1e-5


def test_detect_blank_margins(golden):
    margins = np.array(mtp.detect_blank_margins(golden["margin_sino"].copy(), safety_buffer=4),
                       dtype=np.int64)
    assert np.array_equal(margins, golden["margins"])


def test_apply_detector_crop(golden):
    req = {'sinogram_shape': (11, 40, 36)}
    opt = {'det_row_offset': 1.5, 'det_channel_offset': -0.5,
           'delta_det_row': 0.8, 'delta_det_channel': 1.2}
    req2, opt2 = mtp.apply_detector_crop(dict(req), dict(opt), 3, 5, 2, 6)
    assert np.array_equal(np.array(req2['sinogram_shape']), golden["crop_req_shape"])
    assert np.allclose([opt2['det_row_offset'], opt2['det_channel_offset']],
                       golden["crop_opt"], rtol=1e-12)
    # inputs are not mutated
    assert req['sinogram_shape'] == (11, 40, 36) and opt['det_row_offset'] == 1.5


def test_apply_config_crop(golden):
    out = np.array(mtp.apply_config_crop(
        40, 36, 1.5, -0.5, 0.8, 1.2,
        crop_pixels_top=3, crop_pixels_bottom=5, crop_pixels_sides=2), dtype=np.float64)
    assert np.allclose(out, golden["config_crop"], rtol=1e-12)


def test_apply_cylindrical_mask(golden):
    out_np = mtp.apply_cylindrical_mask(golden["mask_in"].copy(), radial_margin=2,
                                        top_margin=1, bottom_margin=2)
    err = _rel_max(out_np, golden["mask_out"])
    print(f"cylindrical mask rel_max = {err:.2e}")
    assert err < 1e-6
    out_t = mtp.apply_cylindrical_mask(torch.as_tensor(golden["mask_in"].copy()),
                                       radial_margin=2, top_margin=1, bottom_margin=2)
    assert _rel_max(out_t.numpy(), golden["mask_out"]) < 1e-6


def test_beam_hardening_family(golden):
    params = mtp.fit_beam_hardening_curve(golden["p_samples"], golden["bh_samples"],
                                          num_parameters=4)
    err_p = _rel_max(params, golden["bh_params"])
    curve = mtp.apply_beam_hardening_curve(golden["p_samples"], golden["bh_params"])
    err_c = _rel_max(curve, golden["bh_curve"])
    cheb, dom = mtp.fit_inverse_beam_hardening_curve(
        golden["bh_params"], vmin=float(golden["y_domain"][0]),
        vmax=float(golden["y_domain"][1]), degree=8)
    err_i = _rel_max(cheb, golden["cheb_coeffs"])
    inv = mtp.apply_inverse_beam_hardening_curve(
        np.clip(golden["bh_curve"], golden["y_domain"][0], golden["y_domain"][1]),
        golden["cheb_coeffs"], tuple(golden["y_domain"]), clip=True)
    err_v = _rel_max(inv, golden["bh_inverse"])
    print(f"beam hardening rel_max = {err_p:.2e} (fit), {err_c:.2e} (fwd), "
          f"{err_i:.2e} (inv fit), {err_v:.2e} (inv apply)")
    # The two FIT gates are looser than the two APPLY gates on purpose.  Both
    # frameworks' beam-hardening fits stop at the solver's evaluation cap
    # without converging (the fit warns), and a truncated iterative fit is
    # environment-sensitive at the 1e-7 class -- regenerating the goldens in a
    # different environment measured a 9.4e-8 shift.  Curve APPLICATION is a
    # deterministic polynomial evaluation and keeps the float64 gate.
    assert err_p < 1e-6 and err_c < 1e-12 and err_i < 1e-6 and err_v < 1e-12


def test_small_helpers(golden):
    alpha = mtp.compute_scaling_factor(golden["scale_target"], golden["scale_vect"])
    err = abs(alpha - float(golden["scaling_factor"])) / abs(float(golden["scaling_factor"]))
    print(f"scaling factor rel err = {err:.2e}")
    assert err < 1e-5

    out = mtp.put_in_slice(torch.as_tensor(golden["pis_in"].copy()),
                           golden["pis_indices"], -7.0)
    assert np.array_equal(out.numpy(), golden["pis_out"])

    assert abs(mtp.to_alu(25.4, 'mm', 'cm') - float(golden["alu"])) < 1e-12
    assert np.allclose(mtp.unit_vector(np.array([3.0, 4.0, 12.0])), golden["uv"], rtol=1e-12)
    assert np.allclose(mtp.project_vector_to_vector(np.array([1.0, 2.0, 2.0]),
                                                    np.array([0.0, 3.0, 4.0])),
                       golden["pv"], rtol=1e-12)


@pytest.mark.skipif(not os.path.exists(_h5_path), reason="no mbirjax-written cone save golden")
def test_load_mbirjax_cone_save(golden):
    # Golden read of an mbirjax-written file: the two packages share the on-disk layout, and that
    # file carries the older format tag, which the loader still accepts.
    sino, cone_params, opt_params, weights = mtp.load_cone_preprocessing(_h5_path)
    assert np.allclose(sino, golden["sino_trans"], rtol=1e-6, atol=1e-7)
    assert cone_params['sinogram_shape'] == tuple(golden["sino_trans"].shape)
    assert opt_params['sharpness'] == 1.25 and opt_params['det_channel_offset'] == 0.75
    assert weights is not None and weights.shape == golden["sino_trans"].shape


def _write_cone_save(tmp_path, golden, name='pp.h5'):
    """Write a small cone-preprocessing file; return its path and the angles it was given."""
    path = os.path.join(str(tmp_path), name)
    angles = np.linspace(0, np.pi, golden["sino_trans"].shape[0]).astype(np.float32)
    mtp.save_cone_preprocessing(path, golden["sino_trans"],
                                {'sinogram_shape': tuple(golden["sino_trans"].shape),
                                 'angles': angles},
                                {'sharpness': 1.0})
    return path, angles


def test_save_load_round_trip(tmp_path, golden):
    path, angles = _write_cone_save(tmp_path, golden)
    with h5py.File(path, 'r') as f:
        assert f.attrs['format'] == 'mbirtorch_preprocessing_v1'
    sino, cone_params, opt_params, weights = mtp.load_cone_preprocessing(path)
    assert np.array_equal(sino, golden["sino_trans"])
    assert cone_params['sinogram_shape'] == tuple(golden["sino_trans"].shape)
    assert np.allclose(cone_params['angles'], angles)
    assert opt_params == {'sharpness': 1.0} and weights is None


def test_load_accepts_older_format_tag(tmp_path, golden):
    # Files written before the package was renamed carry the mbirjax tag and must keep loading.
    path, _ = _write_cone_save(tmp_path, golden)
    with h5py.File(path, 'r+') as f:
        f.attrs['format'] = 'mbirjax_preprocessing_v1'
    sino, cone_params, opt_params, weights = mtp.load_cone_preprocessing(path)
    assert np.array_equal(sino, golden["sino_trans"])
    assert cone_params['sinogram_shape'] == tuple(golden["sino_trans"].shape)
    assert opt_params == {'sharpness': 1.0} and weights is None


def test_load_accepts_missing_format_tag(tmp_path, golden):
    # The oldest files and files from other tools have no format attribute at all.
    path, _ = _write_cone_save(tmp_path, golden)
    with h5py.File(path, 'r+') as f:
        del f.attrs['format']
    sino, cone_params, opt_params, weights = mtp.load_cone_preprocessing(path)
    assert np.array_equal(sino, golden["sino_trans"])
    assert cone_params['sinogram_shape'] == tuple(golden["sino_trans"].shape)
    assert opt_params == {'sharpness': 1.0} and weights is None


def test_load_rejects_unknown_format_tag(tmp_path, golden):
    path, _ = _write_cone_save(tmp_path, golden)
    with h5py.File(path, 'r+') as f:
        f.attrs['format'] = 'some_other_preprocessing_v9'
    with pytest.raises(ValueError) as excinfo:
        mtp.load_cone_preprocessing(path)
    message = str(excinfo.value)
    # The error has to name the tag found and both tags that would have worked.
    assert 'some_other_preprocessing_v9' in message
    assert 'mbirtorch_preprocessing_v1' in message and 'mbirjax_preprocessing_v1' in message
